---
title: "Untitled"
format: html
---

# Longitudinaldesigns
\setstretch{1.8}
Longitudinalanalyse

\small

Mehrere Messungen ("Repeated Measures") an einer experimentellen Einheit

Annahme der Zufallsfehlerkorrelation innerhalb einer experimentellen Einheit

Typische Beispiele

* Messungen aller Studienbedingungen an einer Proband:in ("Within-Designs")
* Mehrere Messungen an einer Patient:in über den Verlauf einer Psychotherapie

Die Standardtheorie des Allgemeinen Linearen Modells deckt diesen Fall nicht ab

* Annahme der Abwesenheit von Zufallsfehlerkorrelationen zwischen Messpunkten
* Keine mehrfachen Messungen an einer experimentellen Einheit ("Between-Designs")

Aktives Methodenforschungsfeld spätestens seit den 1970er (vgl. @huynh1970)

In der Anwendungen scheinen LMMs momentan Mittel der Wahl (vgl. @detry2016)


# Longitudinaldesigns
\small 

Das Parallelgruppen-Pre-Post-Design-LMMl nach @crager1987 

Change-Score-Analyse
    
* Berechnung der Proband:innen-spezifischen Post-Pre-Differenzen
* Anwendung eines Zweistichproben-T-Tests auf Post-Pre-Differenzen
* Mögliche Nachteile

Pretreatment-Baseline Kovarianzanalyse

* Inklusion der Pre-Daten als Kovariaten in ANCOVA der Post-Daten 
* Mögliche Nachteile

Lord-Paradox nach @lord1967 und @fitzmaurice2001 
 

# Longitudinaldesigns

Longitudinal design

* Single level of clustering
* Natural ordering of the measurments within a cluster.

# Longitudinaldesigns

Repeated-Measures Designvarianten
\vspace{2mm}
\small

$y_i$ : Datenvektor der $i$ten experimentellen Einheit (Proband:in)
\vspace{-2mm}
\center

\flushright
\footnotesize
@tango2017 